name: Validate Intake Formats

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    working-directory: utils

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        id: setup-python
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: |
          poetry install --only main

      - name: Execute tests
        run: |
          poetry run pytest test_formats.py --color=yes -vv --changes
